# Generated by Django 2.1.7 on 2019-04-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app02', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='number',
            field=models.FloatField(null=True),
        ),
    ]
