# Generated by Django 2.1.7 on 2019-04-25 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20190424_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booklist', to='app01.Author'),
        ),
        migrations.AddField(
            model_name='tag',
            name='book',
            field=models.ManyToManyField(related_name='books', to='app01.Book'),
        ),
    ]
