# Generated by Django 2.1.7 on 2019-04-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
            ],
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('classification', models.ManyToManyField(to='app01.Classification')),
            ],
            options={
                'verbose_name_plural': '方向（视频方向）',
                'db_table': 'Direction',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': '难度级别',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, '下线'), (2, '上线')], default=1, verbose_name='状态')),
                ('weight', models.IntegerField(default=0, verbose_name='权重（按从大到小排列）')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('summary', models.CharField(max_length=32, verbose_name='简介')),
                ('img', models.CharField(max_length=32, verbose_name='图片')),
                ('href', models.CharField(max_length=256, verbose_name='视频地址')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=True, to='app01.Classification')),
                ('level', models.ForeignKey(on_delete=True, to='app01.Level')),
            ],
            options={
                'verbose_name_plural': '视频',
                'db_table': 'Video',
            },
        ),
    ]
