# Generated by Django 2.1.7 on 2019-04-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_type',
            field=models.IntegerField(choices=[(0, '普通用户'), (1, '超级用户'), (2, 'VIP用户')], default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(db_column='user', help_text='请输入用户名', max_length=32, null=True, verbose_name='用户名'),
        ),
    ]
